# Generated by Django 4.1 on 2022-09-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(default=2, max_length=6),
            preserve_default=False,
        ),
    ]
